name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build bundler image
        run: |
          docker buildx build \
            --load \
            -t bundler-image:latest \
            --build-arg PAT_USERNAME_FOR_GH=${{ secrets.PAT_USERNAME_FOR_GH }} \
            --build-arg PAT_TOKEN_FOR_GH=${{ secrets.PAT_TOKEN_FOR_GH }} \
            ./bundler

      - name: Build oba image
        run: |
            docker buildx build \
              --load \
              -t oba-image:latest \
              --build-arg PAT_USERNAME_FOR_GH=${{ secrets.PAT_USERNAME_FOR_GH }} \
              --build-arg PAT_TOKEN_FOR_GH=${{ secrets.PAT_TOKEN_FOR_GH }} \
              ./oba

  services:
    name: Services with Bundler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build bundle
        run: |
          PAT_USERNAME_FOR_GH=${{ secrets.PAT_USERNAME_FOR_GH }} \
          PAT_TOKEN_FOR_GH=${{ secrets.PAT_TOKEN_FOR_GH }} \
          docker compose up oba_bundler

      - name: Docker Compose up
        run: |
          PAT_USERNAME_FOR_GH=${{ secrets.PAT_USERNAME_FOR_GH }} \
          PAT_TOKEN_FOR_GH=${{ secrets.PAT_TOKEN_FOR_GH }} \
          docker compose up -d

      - name: Wait for services to be up
        run: sleep 30

      - name: Test the services
        timeout-minutes: 10
        run: |
          chmod +x ./bin/validate.sh
          ./bin/validate.sh

      - name: Docker Compose down
        if: always()
        run: docker compose down

  services_standalone:
    name: Services standalone
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose up
        run: |
          PAT_USERNAME_FOR_GH=${{ secrets.PAT_USERNAME_FOR_GH }} \
          PAT_TOKEN_FOR_GH=${{ secrets.PAT_TOKEN_FOR_GH }} \
          docker compose -f docker-compose.standalone.yml up -d

      - name: Wait for services to be up
        # leave time to download and process the GTFS data
        run: sleep 60

      - name: Test the services
        timeout-minutes: 10
        run: |
          chmod +x ./bin/validate.sh
          ./bin/validate.sh

      # - name: Breakpoint if tests failed
      #   if: failure()
      #   uses: namespacelabs/breakpoint-action@v0
      #   with:
      #     duration: 30m
      #     authorized-users: aaronbrethorst

      - name: Docker Compose down
        if: always()
        run: docker compose down