name: Test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Split the build into two steps to identify which step fails
      - name: Build bundler image
        run: docker buildx build --load -t bundler-image:latest ./bundler

      - name: Build oba image
        run: docker buildx build --load -t oba-image:latest ./oba

  services:
    name: Services with Bundler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose up
        run: docker compose up -d

      - name: Wait for services to be up
        run: sleep 30

      - name: Test the services
        run: |
          chmod +x ./bin/validate.sh
          ./bin/validate.sh

      - name: Docker Compose down
        if: always()
        run: docker compose down

  services_standalone:
    name: Services standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Compose up
        run: docker compose -f docker-compose.standalone.yml up -d

      - name: Wait for services to be up
        # leave time to download and process the GTFS data
        run: sleep 60

      - name: Test the services
        run: |
          chmod +x ./bin/validate.sh
          ./bin/validate.sh

      - name: Docker Compose down
        if: always()
        run: docker compose down